### ISSUE TITLE
Add the ability to handle theme files

### ISSUE THREAD

**Issue by JesseTatasciore** [Evertz/bzlgen#10]
When generating the macro target add the theme file and dependencies where possible

**Comment by mattem** [comment]
This is already possible, set `--ng_generate_theme_binary`. I guess the flag doesn’t make sense when generating for the macro, perhaps we [remove the check](https://github.com/Evertz/bzlgen/blob/master/src/generators/ng/ng.generator.ts#L195)

**Comment by JesseTatasciore** [comment]
Good to know. I might be inclined to flip the flag. That way if people do not want the theme to be setup they can disable it
