### ISSUE TITLE
inconsistent target naming using file and directory

### ISSUE THREAD

**Issue by mattem** [Evertz/bzlgen#20]
Taken from #17 

When you import from a file in another relative package, bzlgen will use the file name as the target, however if you used bzlgen to make that target, it'll be named after the dir, not the file.
Meaning that the target produced from importing relative libs should be the dir name not the filename

Here's my test:

```
    mockfs({
      '/home/workspace/src/some': {
        'one.ts': `import {SOME_CONST} from './nested/two'; `
      },
      '/home/workspace/src/some/nested': {
        'two.ts': `export const SOME_CONST = '';`
      }
    });
```
which produces

```
add deps //src/some/nested:two|//src/some:some
```

But i'd expect to get:

```
add deps //src/some/nested:nested|//src/some:some
```

**Comment by Toxicable** [comment]
Have ya had another chance to look into this one?
I made an attempt but the logic in there for this is a little confusing :p
